// domain/repositories/notification_repository.dart — NotificationRepository interface (domain layer).

import 'package:aion/features/tickets/domain/entities/notification.dart';

/// Persists coding-execution/SDD-stage-chat outcome notifications. See
/// `aion-arch/changes/pr-metadata-and-notification-center/design.md` §2.
abstract interface class NotificationRepository {
  /// Inserts a new, unread [Notification]. [id] is generated by the
  /// caller (matches every other repository's `id: ''`-then-DAO-
  /// generates convention — see `CommentRepository.addComment`).
  Future<void> addNotification(Notification notification);

  /// Returns the [limit] most recent notifications (any read state),
  /// newest first.
  Future<List<Notification>> getRecent({int limit = 20});

  /// Returns the count of notifications with `readAt == null`.
  Future<int> getUnreadCount();

  /// Sets [id]'s `readAt` to now. No-ops if [id] doesn't exist or is
  /// already read.
  Future<void> markRead(String id);

  /// Sets every currently-unread notification's `readAt` to now.
  Future<void> markAllRead();

  /// Returns [ticketId]'s most recent notification of [kind], or `null`
  /// if none exists. Feeds `TicketDetailLoaded.executionPrSubLine`
  /// (§4.6) — avoids re-deriving PR metadata from the comment thread a
  /// second time when a notification row already holds the formatted
  /// text.
  Future<Notification?> getMostRecentForTicket(
    String ticketId,
    NotificationKind kind,
  );
}
