// domain/entities/ticket.dart — Ticket entity (domain layer).

import 'dart:typed_data';

import 'package:equatable/equatable.dart';

import 'package:aion/features/tickets/domain/enums/inbox_purpose.dart';
import 'package:aion/features/tickets/domain/enums/sdd_stage.dart';
import 'package:aion/features/tickets/domain/enums/ticket_complexity.dart';
import 'package:aion/features/tickets/domain/enums/ticket_estimation_source.dart';
import 'package:aion/features/tickets/domain/enums/ticket_priority.dart';
import 'package:aion/features/tickets/domain/enums/ticket_severity.dart';
import 'package:aion/features/tickets/domain/enums/ticket_status.dart';
import 'package:aion/features/tickets/domain/enums/ticket_sync_status.dart';
import 'package:aion/features/tickets/domain/enums/ticket_type.dart';

/// The central entity of Aion — every other concept (epic, story, task,
/// resource, page, chat) is a [Ticket] distinguished by [type].
class Ticket extends Equatable {
  /// Internal UUID v4 primary key, used for all relations (`parentId`,
  /// links, comments). Never shown to the user.
  final String id;

  /// Human-readable identifier (e.g. `"AIO-42"`) — display and search key.
  /// Generated by [TicketRepository.createTicket]; empty on entities not
  /// yet persisted.
  final String ticketId;

  /// What kind of ticket this is.
  final TicketType type;

  /// Short display title.
  final String title;

  /// Optional long-form description.
  final String? description;

  /// Current workflow state.
  final TicketStatus status;

  /// Urgency of the ticket. Defaults to [TicketPriority.none].
  final TicketPriority priority;

  /// UUID of the structural parent ticket, if any. Self-referencing;
  /// models the parent/child hierarchy exclusively — never a link type.
  final String? parentId;

  /// Semantic embedding for similarity search. Nullable until the
  /// on-device [EmbeddingProvider](../../../core/contracts/embedding_provider.dart)
  /// generates one — regenerated asynchronously whenever [title]/
  /// [description] change (ticket save never waits on it). Never
  /// committed to git, not even as a hash.
  final Uint8List? embedding;

  /// How this ticket's database record relates to its projected Markdown
  /// file. Always [TicketSyncStatus.synced] for every type except
  /// `resource`/`page`, which have a bidirectional file the user can
  /// hand-edit.
  final TicketSyncStatus syncStatus;

  /// Estimated effort in minutes. Editable via `TicketMetadataSection`'s
  /// Estimate field; also the base value [estimateRollup] sums up its
  /// live descendant subtree from. See [estimateSource] for where the
  /// current value came from.
  final int? estimate;

  /// Time spent in minutes. Editable via `TicketMetadataSection`'s Time
  /// Spent field; also the base value [timeSpentRollup] sums up its live
  /// descendant subtree from.
  final int? timeSpent;

  /// When the ticket was created.
  final DateTime createdAt;

  /// When the ticket was last modified.
  final DateTime updatedAt;

  /// When this ticket was moved to trash (soft-deleted). `null` means the
  /// ticket is live. Set by [TicketRepository.trashTicket]/`trashTickets`,
  /// cleared by [TicketRepository.restoreTicket].
  final DateTime? deletedAt;

  /// Rough size estimate. `null` until sized. See [complexitySource] for
  /// where the current value came from.
  final TicketComplexity? complexity;

  /// This ticket's SDD-cycle progress. `null` until the cycle starts.
  /// Meaningful only for [TicketType.epic]/[TicketType.story] — see
  /// [SddStage]. Written only via `TicketsCubit.advanceSddStage`, never
  /// through the generic [copyWith]-based [TicketRepository.updateTicket]
  /// path other fields use, so its precondition can't be bypassed by a
  /// plain edit.
  final SddStage? sddStage;

  /// Impact of a [TicketType.bug] ticket. `null` until sized. Meaningless
  /// for every other type.
  final TicketSeverity? severity;

  /// Reproduction steps for a [TicketType.bug] ticket. `null` until set.
  /// Meaningless for every other type.
  final String? stepsToReproduce;

  /// What should have happened, for a [TicketType.bug] ticket. `null`
  /// until set. Meaningless for every other type.
  final String? expectedBehavior;

  /// What actually happened, for a [TicketType.bug] ticket. `null` until
  /// set. Meaningless for every other type.
  final String? actualBehavior;

  /// The Inbox brain-dump purpose's suggested promotion target (Epic or
  /// Bug), read by the widened promote-chooser to pre-select which target
  /// type to promote to. Meaningful only for [TicketType.signal] tickets;
  /// `null` for every ticket not created by the brain-dump purpose, and
  /// `null` for a brain-dump signal until the model actually classifies it
  /// (defensive default — a parse failure on one block shouldn't crash
  /// the rest of the reply).
  final TicketType? suggestedType;

  /// Which Inbox purpose spawned this ticket, if any. Set exactly once, at
  /// creation, on the parentless `chat` ticket an Inbox launch spawns.
  /// `null` for every other ticket, including every other `chat`. See
  /// [InboxPurpose].
  final InboxPurpose? inboxPurpose;

  /// Derived, recursive rollup of this ticket's own [estimate] plus every
  /// live descendant's effective value (a child's own rollup if it has
  /// children, its own [estimate] otherwise). `null` when this ticket has
  /// no live children — the UI falls back to [estimate] directly in that
  /// case, so a leaf never shows a redundant "rollup of itself." Computed
  /// and persisted only by `TicketsCubit`/`TrashCubit`'s rollup-recompute
  /// walk (see `computeRollups` in
  /// `domain/utils/ticket_rollup_calculator.dart`); never part of
  /// [copyWith] — same treatment as [sddStage], written only through a
  /// dedicated repository method (`TicketRepository.updateRollup`) so a
  /// plain content edit can't accidentally clobber it.
  final int? estimateRollup;

  /// Same as [estimateRollup], for [timeSpent].
  final int? timeSpentRollup;

  /// Where the current [complexity] value came from, or `null` if
  /// [complexity] itself is unset. Written only by `TicketRepository`'s
  /// dedicated methods — see [complexity]'s dartdoc and
  /// `aion-arch/changes/ai-assisted-complexity-and-estimate-suggestions/design.md`
  /// §1.2. Never part of [copyWith].
  final TicketEstimationSource? complexitySource;

  /// Same as [complexitySource], for [estimate].
  final TicketEstimationSource? estimateSource;

  /// Creates a [Ticket]. [priority] defaults to [TicketPriority.none].
  const Ticket({
    required this.id,
    required this.ticketId,
    required this.type,
    required this.title,
    this.description,
    required this.status,
    this.priority = TicketPriority.none,
    this.parentId,
    this.embedding,
    this.syncStatus = TicketSyncStatus.synced,
    this.estimate,
    this.timeSpent,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    this.complexity,
    this.sddStage,
    this.severity,
    this.stepsToReproduce,
    this.expectedBehavior,
    this.actualBehavior,
    this.suggestedType,
    this.inboxPurpose,
    this.estimateRollup,
    this.timeSpentRollup,
    this.complexitySource,
    this.estimateSource,
  });

  @override
  List<Object?> get props => [
    id,
    ticketId,
    type,
    title,
    description,
    status,
    priority,
    parentId,
    embedding,
    syncStatus,
    estimate,
    timeSpent,
    createdAt,
    updatedAt,
    deletedAt,
    complexity,
    sddStage,
    severity,
    stepsToReproduce,
    expectedBehavior,
    actualBehavior,
    suggestedType,
    inboxPurpose,
    estimateRollup,
    timeSpentRollup,
    complexitySource,
    estimateSource,
  ];

  /// Returns a copy of this ticket with the given fields replaced.
  /// [description], [estimate], [timeSpent], [complexity], [severity],
  /// [stepsToReproduce], [expectedBehavior], [actualBehavior],
  /// [suggestedType], and [inboxPurpose] are nullable and therefore take a
  /// zero-arg setter instead of a bare value — pass `() => null` to
  /// explicitly clear one of them, or omit the parameter entirely to leave
  /// it unchanged. A plain `?? this.x` fallback can't tell "not passed"
  /// apart from "explicitly set to null," since both look like `null` at
  /// the call site. `id`, `ticketId`, `parentId`, `embedding`,
  /// `syncStatus`, `createdAt`, `sddStage`, `estimateRollup`, and
  /// `timeSpentRollup` are never mutated by this method — `sddStage` is
  /// written only via `TicketsCubit.advanceSddStage`, and
  /// `estimateRollup`/`timeSpentRollup` are written only via
  /// `TicketRepository.updateRollup`, so neither's precondition can be
  /// bypassed by a plain edit.
  Ticket copyWith({
    String? title,
    TicketFieldSetter<String?>? description,
    TicketStatus? status,
    TicketPriority? priority,
    TicketType? type,
    TicketFieldSetter<int?>? estimate,
    TicketFieldSetter<int?>? timeSpent,
    TicketFieldSetter<TicketComplexity?>? complexity,
    TicketFieldSetter<TicketSeverity?>? severity,
    TicketFieldSetter<String?>? stepsToReproduce,
    TicketFieldSetter<String?>? expectedBehavior,
    TicketFieldSetter<String?>? actualBehavior,
    TicketFieldSetter<TicketType?>? suggestedType,
    TicketFieldSetter<InboxPurpose?>? inboxPurpose,
    DateTime? updatedAt,
  }) {
    return Ticket(
      id: id,
      ticketId: ticketId,
      type: type ?? this.type,
      title: title ?? this.title,
      description: description != null ? description() : this.description,
      status: status ?? this.status,
      priority: priority ?? this.priority,
      parentId: parentId,
      embedding: embedding,
      syncStatus: syncStatus,
      estimate: estimate != null ? estimate() : this.estimate,
      timeSpent: timeSpent != null ? timeSpent() : this.timeSpent,
      createdAt: createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      complexity: complexity != null ? complexity() : this.complexity,
      sddStage: sddStage,
      severity: severity != null ? severity() : this.severity,
      stepsToReproduce: stepsToReproduce != null
          ? stepsToReproduce()
          : this.stepsToReproduce,
      expectedBehavior: expectedBehavior != null
          ? expectedBehavior()
          : this.expectedBehavior,
      actualBehavior: actualBehavior != null
          ? actualBehavior()
          : this.actualBehavior,
      suggestedType: suggestedType != null
          ? suggestedType()
          : this.suggestedType,
      inboxPurpose: inboxPurpose != null ? inboxPurpose() : this.inboxPurpose,
      estimateRollup: estimateRollup,
      timeSpentRollup: timeSpentRollup,
    );
  }
}

/// A zero-arg setter used by [Ticket.copyWith] for nullable fields, so a
/// caller can distinguish "leave unchanged" (omit the parameter) from
/// "explicitly clear to null" (pass `() => null`). Plain Dart function
/// type — no import needed, keeping the domain layer Flutter-free. Public
/// (not a private typedef) since it appears in `copyWith`'s public
/// signature.
typedef TicketFieldSetter<T> = T Function();
