// domain/entities/ticket.dart — Ticket entity (domain layer).

import 'dart:typed_data';

import 'package:equatable/equatable.dart';

import 'package:aion/features/tickets/domain/enums/ticket_priority.dart';
import 'package:aion/features/tickets/domain/enums/ticket_status.dart';
import 'package:aion/features/tickets/domain/enums/ticket_type.dart';

/// The central entity of Aion — every other concept (epic, story, task,
/// resource, page, chat) is a [Ticket] distinguished by [type].
class Ticket extends Equatable {
  /// Internal UUID v4 primary key, used for all relations (`parentId`,
  /// links, comments). Never shown to the user.
  final String id;

  /// Human-readable identifier (e.g. `"AIO-42"`) — display and search key.
  /// Generated by [TicketRepository.createTicket]; empty on entities not
  /// yet persisted.
  final String ticketId;

  /// What kind of ticket this is.
  final TicketType type;

  /// Short display title.
  final String title;

  /// Optional long-form description.
  final String? description;

  /// Current workflow state.
  final TicketStatus status;

  /// Urgency of the ticket. Defaults to [TicketPriority.none].
  final TicketPriority priority;

  /// UUID of the structural parent ticket, if any. Self-referencing;
  /// models the parent/child hierarchy exclusively — never a link type.
  final String? parentId;

  /// Semantic embedding for similarity search. Nullable — population is
  /// deferred to a future change; the column exists so no migration is
  /// needed later.
  final Uint8List? embedding;

  /// Estimated effort in minutes. No UI reads or writes this yet.
  final int? estimate;

  /// Time spent in minutes. No UI reads or writes this yet.
  final int? timeSpent;

  /// When the ticket was created.
  final DateTime createdAt;

  /// When the ticket was last modified.
  final DateTime updatedAt;

  /// Creates a [Ticket]. [priority] defaults to [TicketPriority.none].
  const Ticket({
    required this.id,
    required this.ticketId,
    required this.type,
    required this.title,
    this.description,
    required this.status,
    this.priority = TicketPriority.none,
    this.parentId,
    this.embedding,
    this.estimate,
    this.timeSpent,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  List<Object?> get props => [
        id,
        ticketId,
        type,
        title,
        description,
        status,
        priority,
        parentId,
        embedding,
        estimate,
        timeSpent,
        createdAt,
        updatedAt,
      ];
}
