// data/models/ticket_model.dart — Drift table definitions for tickets (data layer).

import 'package:drift/drift.dart';

/// Drift table backing [Ticket](../../domain/entities/ticket.dart). Row type
/// is generated as `TicketData`. No FK constraints — integrity is enforced
/// at the repository layer.
@DataClassName('TicketData')
class TicketsTable extends Table {
  @override
  String get tableName => 'tickets';

  /// Internal UUID v4 primary key.
  TextColumn get id => text()();

  /// Human-readable identifier (e.g. `"AIO-42"`), unique. Generated by
  /// [TicketDao.insertTicket] from [TicketIdSequenceTable].
  TextColumn get ticketId => text().named('ticket_id').unique()();

  /// `TicketType.name` string.
  TextColumn get type => text()();

  /// Short display title.
  TextColumn get title => text()();

  /// Optional long-form description.
  TextColumn get description => text().nullable()();

  /// `TicketStatus.name` string.
  TextColumn get status => text()();

  /// `TicketPriority.name` string. Defaults to `'none'`.
  TextColumn get priority => text().withDefault(const Constant('none'))();

  /// Self-referencing UUID for the structural parent ticket, if any.
  TextColumn get parentId => text().named('parent_id').nullable()();

  /// Semantic embedding BLOB, populated asynchronously by
  /// `EmbeddingProvider` whenever `title`/`description` change.
  BlobColumn get embedding => blob().nullable()();

  /// `TicketSyncStatus.name` string. Defaults to `'synced'`.
  TextColumn get syncStatus =>
      text().named('sync_status').withDefault(const Constant('synced'))();

  /// Estimated effort in minutes.
  IntColumn get estimate => integer().nullable()();

  /// Time spent in minutes.
  IntColumn get timeSpent => integer().named('time_spent').nullable()();

  /// Unix milliseconds.
  IntColumn get createdAt => integer().named('created_at')();

  /// Unix milliseconds.
  IntColumn get updatedAt => integer().named('updated_at')();

  /// When this ticket was moved to trash (soft-deleted). `null` means the
  /// ticket is live. Set by [TicketDao.softDeleteByIds], cleared by
  /// [TicketDao.restoreByIds]. Unix milliseconds.
  IntColumn get deletedAt => integer().named('deleted_at').nullable()();

  /// `TicketComplexity.name`, nullable.
  TextColumn get complexity => text().nullable()();

  /// `SddStage.name`, nullable. Written only via
  /// `TicketDao.updateSddStage` — see
  /// `TicketRepository.updateTicketSddStage`.
  TextColumn get sddStage => text().named('sdd_stage').nullable()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Singleton counter table used to derive the next [TicketsTable.ticketId]
/// suffix. Always exactly one row (`id: 1`), incremented transactionally by
/// [TicketDao.insertTicket]. Row type is generated as `TicketIdSequenceData`.
@DataClassName('TicketIdSequenceData')
class TicketIdSequenceTable extends Table {
  @override
  String get tableName => 'ticket_id_sequence';

  /// Always `1` — this table is a single-row singleton.
  IntColumn get id => integer()();

  /// The last-issued sequence number. Next ticket gets `seq + 1`.
  IntColumn get seq => integer().withDefault(const Constant(0))();

  @override
  Set<Column> get primaryKey => {id};
}
