// data/models/ticket_model.dart — Drift table definitions for tickets (data layer).

import 'package:drift/drift.dart';

/// Drift table backing [Ticket](../../domain/entities/ticket.dart). Row type
/// is generated as `TicketData`. No FK constraints — integrity is enforced
/// at the repository layer.
@DataClassName('TicketData')
class TicketsTable extends Table {
  @override
  String get tableName => 'tickets';

  /// Internal UUID v4 primary key.
  TextColumn get id => text()();

  /// Human-readable identifier (e.g. `"AIO-42"`), unique. Generated by
  /// [TicketDao.insertTicket] from [TicketIdSequenceTable].
  TextColumn get ticketId => text().named('ticket_id').unique()();

  /// `TicketType.name` string.
  TextColumn get type => text()();

  /// Short display title.
  TextColumn get title => text()();

  /// Optional long-form description.
  TextColumn get description => text().nullable()();

  /// A project-defined `WorkflowStatus.name` string (see
  /// `Ticket.status`'s dartdoc) — was `TicketStatus.name` before
  /// `AIO-549`.
  TextColumn get status => text()();

  /// `TicketPriority.name` string. Defaults to `'none'`.
  TextColumn get priority => text().withDefault(const Constant('none'))();

  /// Self-referencing UUID for the structural parent ticket, if any.
  TextColumn get parentId => text().named('parent_id').nullable()();

  /// Semantic embedding BLOB, populated asynchronously by
  /// `EmbeddingProvider` whenever `title`/`description` change.
  BlobColumn get embedding => blob().nullable()();

  /// `TicketSyncStatus.name` string. Defaults to `'synced'`.
  TextColumn get syncStatus =>
      text().named('sync_status').withDefault(const Constant('synced'))();

  /// Estimated effort in minutes.
  IntColumn get estimate => integer().nullable()();

  /// Time spent in minutes.
  IntColumn get timeSpent => integer().named('time_spent').nullable()();

  /// Unix milliseconds.
  IntColumn get createdAt => integer().named('created_at')();

  /// Unix milliseconds.
  IntColumn get updatedAt => integer().named('updated_at')();

  /// When this ticket was moved to trash (soft-deleted). `null` means the
  /// ticket is live. Set by [TicketDao.softDeleteByIds], cleared by
  /// [TicketDao.restoreByIds]. Unix milliseconds.
  IntColumn get deletedAt => integer().named('deleted_at').nullable()();

  /// `TicketComplexity.name`, nullable.
  TextColumn get complexity => text().nullable()();

  /// `SddStage.name`, nullable. Written only via
  /// `TicketDao.updateSddStage` — see
  /// `TicketRepository.updateTicketSddStage`.
  TextColumn get sddStage => text().named('sdd_stage').nullable()();

  /// `TicketSeverity.name`, nullable. Meaningful only for
  /// `TicketType.bug`.
  TextColumn get severity => text().nullable()();

  /// Reproduction steps. Meaningful only for `TicketType.bug`.
  TextColumn get stepsToReproduce =>
      text().named('steps_to_reproduce').nullable()();

  /// Expected behavior. Meaningful only for `TicketType.bug`.
  TextColumn get expectedBehavior =>
      text().named('expected_behavior').nullable()();

  /// Actual behavior. Meaningful only for `TicketType.bug`.
  TextColumn get actualBehavior =>
      text().named('actual_behavior').nullable()();

  /// `TicketType.name`, nullable. Meaningful only for `TicketType.idea`
  /// tickets created by the Inbox brain-dump purpose — the model's
  /// suggested promotion target (epic or bug).
  TextColumn get suggestedType =>
      text().named('suggested_type').nullable()();

  /// `InboxPurpose.name`, nullable. Set exactly once, at creation, on the
  /// parentless `chat` ticket an Inbox launch spawns. `null` for every
  /// other ticket.
  TextColumn get inboxPurpose =>
      text().named('inbox_purpose').nullable()();

  /// Derived rollup of `estimate` across this ticket's live structural
  /// subtree. `null` if this ticket has no live children. Written only by
  /// `TicketRepository.updateRollup`, never by a plain ticket edit.
  IntColumn get estimateRollup =>
      integer().named('estimate_rollup').nullable()();

  /// Derived rollup of `timeSpent` across this ticket's live structural
  /// subtree. `null` if this ticket has no live children. Written only by
  /// `TicketRepository.updateRollup`, never by a plain ticket edit.
  IntColumn get timeSpentRollup =>
      integer().named('time_spent_rollup').nullable()();

  /// `TicketEstimationSource.name`, nullable. `null` iff `complexity` is
  /// also `null` — see `Ticket.complexitySource`.
  TextColumn get complexitySource =>
      text().named('complexity_source').nullable()();

  /// Same as [complexitySource], for [estimate].
  TextColumn get estimateSource =>
      text().named('estimate_source').nullable()();

  /// Low end of the pre-execution token-cost estimate range, nullable.
  /// Written only by `TicketTokenPredictor` via
  /// `TicketRepository.applyTokenPrediction`.
  IntColumn get predictedExecutionTokensLow =>
      integer().named('predicted_execution_tokens_low').nullable()();

  /// High end of the pre-execution token-cost estimate range, nullable.
  /// See [predictedExecutionTokensLow].
  IntColumn get predictedExecutionTokensHigh =>
      integer().named('predicted_execution_tokens_high').nullable()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Singleton counter table used to derive the next [TicketsTable.ticketId]
/// suffix. Always exactly one row (`id: 1`), incremented transactionally by
/// [TicketDao.insertTicket]. Row type is generated as `TicketIdSequenceData`.
@DataClassName('TicketIdSequenceData')
class TicketIdSequenceTable extends Table {
  @override
  String get tableName => 'ticket_id_sequence';

  /// Always `1` — this table is a single-row singleton.
  IntColumn get id => integer()();

  /// The last-issued sequence number. Next ticket gets `seq + 1`.
  IntColumn get seq => integer().withDefault(const Constant(0))();

  @override
  Set<Column> get primaryKey => {id};
}
